import { StyleSheet } from 'react-native';

import { colors, radius, shadow } from '../../theme';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 120,
    gap: 18,
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: colors.primaryDeep,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  loadingBadge: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTitle: {
    marginTop: 22,
    fontSize: 34,
    fontWeight: '900',
    color: colors.white,
  },
  loadingText: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 15,
    lineHeight: 22,
    color: 'rgba(255,255,255,0.82)',
  },
  headerWrap: {
    gap: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerCopy: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: colors.ink,
    textAlign: 'right',
  },
  headerSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.muted,
    textAlign: 'right',
  },
  headerAction: {
    marginStart: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
  },
  headerActionText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primaryDeep,
  },
  card: {
    padding: 18,
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    gap: 14,
    ...shadow.card,
  },
  splitColumn: {
    gap: 14,
  },
  listColumn: {
    gap: 12,
  },
  signalCard: {
    padding: 18,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    gap: 12,
    ...shadow.card,
  },
  signalTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  signalId: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.ink,
    textAlign: 'right',
  },
  signalMeta: {
    marginTop: 4,
    fontSize: 12,
    color: colors.muted,
    textAlign: 'right',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
  },
  statusWaiting: {
    backgroundColor: '#FFF2CB',
  },
  statusOnWay: {
    backgroundColor: '#DDEFF7',
  },
  statusArrived: {
    backgroundColor: colors.primarySoft,
  },
  statusPicked: {
    backgroundColor: '#D9F0E2',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primaryDeep,
  },
  signalText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
    textAlign: 'right',
  },
  floatingAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 54,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    ...shadow.card,
  },
  floatingAddButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.white,
  },
  emptyCard: {
    padding: 20,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    ...shadow.card,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.text,
    textAlign: 'right',
  },
  qrCard: {
    padding: 18,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    alignItems: 'center',
    gap: 10,
    ...shadow.card,
  },
  qrTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.ink,
  },
  qrSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    color: colors.muted,
  },
  qrGrid: {
    width: 180,
    height: 180,
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderWidth: 10,
    borderColor: colors.ink,
    backgroundColor: colors.white,
  },
  qrCell: {
    width: '12.5%',
    height: '12.5%',
    backgroundColor: colors.white,
  },
  qrCellFilled: {
    backgroundColor: colors.ink,
  },
  qrCodeText: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.ink,
    letterSpacing: 1,
  },
  choiceCard: {
    padding: 20,
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'flex-end',
    ...shadow.card,
  },
  choiceCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  choiceTitle: {
    marginTop: 14,
    fontSize: 22,
    fontWeight: '800',
    color: colors.ink,
    textAlign: 'right',
  },
  choiceSubtitle: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
    textAlign: 'right',
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'right',
  },
  input: {
    height: 50,
    paddingHorizontal: 14,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    textAlign: 'right',
  },
  textArea: {
    height: 110,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  readonlyValue: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceStrong,
    color: colors.primaryDeep,
    fontWeight: '800',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
  },
  chipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  chipText: {
    fontWeight: '700',
    color: colors.text,
  },
  chipTextActive: {
    color: colors.primaryDeep,
  },
  mapCard: {
    height: 260,
    borderRadius: radius.lg,
    overflow: 'hidden',
  },
  largeMapCard: {
    height: 320,
    borderRadius: radius.lg,
    overflow: 'hidden',
  },
  driverMapCard: {
    height: 220,
    borderRadius: radius.md,
    overflow: 'hidden',
  },
  mapView: {
    flex: 1,
  },
  mapBadge: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  mapBadgeText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: colors.ink,
  },
  infoBanner: {
    padding: 14,
    borderRadius: radius.md,
    backgroundColor: '#DDEFF7',
  },
  infoBannerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.navy,
    textAlign: 'right',
  },
  infoBannerText: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 19,
    color: '#36556B',
    textAlign: 'right',
  },
  primaryButton: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.white,
  },
  detailRow: {
    gap: 4,
  },
  detailLabel: {
    fontSize: 12,
    color: colors.muted,
    textAlign: 'right',
  },
  detailValue: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '700',
    color: colors.ink,
    textAlign: 'right',
  },
  fakeCardBox: {
    padding: 16,
    borderRadius: radius.md,
    backgroundColor: colors.navy,
  },
  fakeCardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.white,
    textAlign: 'right',
  },
  fakeCardText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(255,255,255,0.82)',
    textAlign: 'right',
  },
  pointsHero: {
    alignItems: 'center',
    paddingVertical: 28,
    borderRadius: radius.lg,
    backgroundColor: colors.primaryDeep,
    ...shadow.card,
  },
  pointsValue: {
    fontSize: 52,
    fontWeight: '900',
    color: colors.white,
  },
  pointsLabel: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: '800',
    color: '#C8F1DB',
  },
  pointsText: {
    marginTop: 10,
    paddingHorizontal: 26,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
    color: 'rgba(255,255,255,0.86)',
  },
  truckMarker: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.primaryDeep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.ink,
    textAlign: 'right',
  },
});
